const baseEmployees = [
  {
    id: 'E001',
    initials: 'LP',
    name: '林品妤',
    department: '節目部',
    title: '製作企劃',
    manager: '周主任',
    hireDate: '2021-08-16',
    tenure: '4年9個月',
    status: '在職',
    risk: '低',
    contractType: '不定期契約',
    shiftType: '日班',
    profileCompleteness: 98,
    pendingTasks: 2,
    lastChangeShort: '轉任',
    lastChange: '轉任專案組，主管與成本中心同步更新',
    modules: {
      contract: { value: '正常', detail: '年資起計日 2021-08-16，附件完整' },
      attendance: { value: '無異常', detail: '本月請假 1 日，加班 4 小時' },
      payroll: { value: '已檢核', detail: '津貼、保險扣繳與獎金資料一致' },
      shift: { value: '日班', detail: '固定班別，無跨部門支援' },
      movement: { value: '3 筆', detail: '部門轉任、職稱更新、主管異動' },
    },
    timeline: [
      { date: '2026/05', title: '轉任專案組', detail: '部門、主管與成本中心同步更新' },
      { date: '2025/11', title: '職稱調整', detail: '製作助理調整為製作企劃' },
      { date: '2024/08', title: '薪資級距更新', detail: '年度調薪紀錄保留' },
    ],
    detailCards: [
      { label: '契約提醒', value: '正常', detail: '附件與年資資料齊全' },
      { label: '本月出勤', value: '21 天', detail: '補登 0 筆，異常 0 筆' },
      { label: '薪資狀態', value: '已檢核', detail: '津貼與保險扣繳一致' },
    ],
    records: [
      { time: '09:18', title: '資料異動', detail: '成本中心與主管資訊更新' },
      { time: '09:26', title: '請假紀錄', detail: '本月年假 1 日已核准' },
      { time: '09:34', title: '薪資資料', detail: '加班 4 小時已納入月結' },
    ],
  },
  {
    id: 'E014',
    initials: 'WC',
    name: '吳佳蓉',
    department: '新聞部',
    title: '採訪編輯',
    manager: '陳副理',
    hireDate: '2019-03-04',
    tenure: '7年2個月',
    status: '在職',
    risk: '中',
    contractType: '不定期契約',
    shiftType: '輪班',
    profileCompleteness: 94,
    pendingTasks: 5,
    lastChangeShort: '加班',
    lastChange: '加班時數偏高，月結前需主管覆核',
    modules: {
      contract: { value: '正常', detail: '契約與年資資料已完成建檔' },
      attendance: { value: '需覆核', detail: '連續兩週加班偏高，觸發提醒' },
      payroll: { value: '待覆核', detail: '加班費與夜點津貼納入月結試算' },
      shift: { value: '輪班', detail: '新聞採訪輪值，支援多班制規則' },
      movement: { value: '5 筆', detail: '排班調整與津貼異動已保留紀錄' },
    },
    timeline: [
      { date: '2026/05', title: '加班費覆核', detail: '月結前需主管確認異常時數' },
      { date: '2026/03', title: '班別調整', detail: '晚班支援改為輪值班表' },
      { date: '2025/09', title: '津貼異動', detail: '夜間採訪津貼規則更新' },
    ],
    detailCards: [
      { label: '契約提醒', value: '正常', detail: '續約期限充足' },
      { label: '本月出勤', value: '18 天', detail: '異常 2 筆，補登 1 筆' },
      { label: '薪資狀態', value: '待覆核', detail: '夜點津貼與加班費同步檢查中' },
    ],
    records: [
      { time: '08:52', title: '加班提醒', detail: '本週已達部門提醒門檻' },
      { time: '09:10', title: '班表調整', detail: '輪班規則更新為晚班支援' },
      { time: '09:28', title: '薪資資料', detail: '夜點津貼待主管覆核' },
    ],
  },
  {
    id: 'E027',
    initials: 'CB',
    name: '陳柏翰',
    department: '資訊部',
    title: '系統工程師',
    manager: '林經理',
    hireDate: '2020-12-01',
    tenure: '5年5個月',
    status: '在職',
    risk: '權限',
    contractType: '不定期契約',
    shiftType: '彈性班',
    profileCompleteness: 100,
    pendingTasks: 1,
    lastChangeShort: '權限',
    lastChange: '系統維運權限調整，AD 群組與 RBAC 已同步',
    modules: {
      contract: { value: '正常', detail: '契約附件與保密協議完整' },
      attendance: { value: '正常', detail: '彈性工時符合規則' },
      payroll: { value: '已檢核', detail: '專業津貼與保險扣繳一致' },
      shift: { value: '彈性班', detail: '支援夜間維運補休規則' },
      movement: { value: '4 筆', detail: '權限、職務與專案支援異動' },
    },
    timeline: [
      { date: '2026/05', title: 'RBAC 權限調整', detail: '維運角色異動已同步' },
      { date: '2026/01', title: '彈性班設定', detail: '夜間維運支援納入排班規則' },
      { date: '2025/06', title: '職務更新', detail: '系統管理職務範圍調整' },
    ],
    detailCards: [
      { label: '契約提醒', value: '正常', detail: '保密協議與契約完整' },
      { label: '本月出勤', value: '20 天', detail: '夜間維運補休 1 次' },
      { label: '薪資狀態', value: '已檢核', detail: '專業津貼與補休設定一致' },
    ],
    records: [
      { time: '09:06', title: '權限更新', detail: 'AD 與系統角色同步完成' },
      { time: '09:21', title: '排班設定', detail: '夜間維運補休規則已套用' },
      { time: '09:39', title: '出勤資料', detail: '彈性工時無異常' },
    ],
  },
  {
    id: 'E041',
    initials: 'WA',
    name: '王以安',
    department: '人資室',
    title: '薪酬專員',
    manager: '黃主任',
    hireDate: '2018-10-22',
    tenure: '7年7個月',
    status: '在職',
    risk: '低',
    contractType: '不定期契約',
    shiftType: '日班',
    profileCompleteness: 99,
    pendingTasks: 3,
    lastChangeShort: '薪資',
    lastChange: '薪資月結參數更新，保險扣繳與津貼規則同步',
    modules: {
      contract: { value: '正常', detail: '續約與附件提醒無異常' },
      attendance: { value: '正常', detail: '本月無異常出勤事件' },
      payroll: { value: '檢核中', detail: '月初提前給薪批次準備中' },
      shift: { value: '日班', detail: '固定班別與例假規則一致' },
      movement: { value: '6 筆', detail: '薪資參數、角色權限與職務調整' },
    },
    timeline: [
      { date: '2026/05', title: '薪資參數更新', detail: '保險扣繳與津貼規則同步' },
      { date: '2026/02', title: '角色權限調整', detail: '薪酬資料匯出權限覆核' },
      { date: '2025/08', title: '職等調整', detail: '年度考核後薪等更新' },
    ],
    detailCards: [
      { label: '契約提醒', value: '正常', detail: '附件與歷程皆完整' },
      { label: '本月出勤', value: '22 天', detail: '補登 0 筆，請假 0 筆' },
      { label: '薪資狀態', value: '檢核中', detail: '月初提前給薪批次準備中' },
    ],
    records: [
      { time: '08:58', title: '薪資批次', detail: '月結參數更新完成' },
      { time: '09:17', title: '保險資料', detail: '扣繳規則已同步' },
      { time: '09:41', title: '角色設定', detail: '薪酬資料檢視權限已確認' },
    ],
  },
]

const extraEmployees = [
  ['E052', 'ZH', '張皓', '製作部', '導播助理', '林副理', '2022-06-13', '3年11個月', '日班', '低', '正常', '本月出勤 20 天，補登 1 筆'],
  ['E057', 'LY', '劉妍', '公關部', '品牌專員', '周經理', '2023-01-09', '3年4個月', '日班', '低', '已檢核', '活動支援班表 2 次'],
  ['E063', 'HS', '何紹安', '工程部', '攝影工程師', '2017-11-20', '8年6個月', '輪班', '中', '待覆核', '夜間班別 6 次'],
  ['E071', 'CY', '蔡妤', '節目部', '內容企劃', '周主任', '2024-02-05', '2年3個月', '日班', '低', '正常', '年假 1 日'],
  ['E082', 'KM', '柯明哲', '資訊部', '資料庫管理師', '2016-07-18', '9年10個月', '彈性班', '權限', '已檢核', '維運支援 2 次'],
  ['E093', 'SL', '沈立安', '新聞部', '文字記者', '2021-04-12', '5年1個月', '輪班', '中', '待覆核', '補登 2 筆'],
  ['E104', 'JT', '簡庭', '人資室', '招募專員', '2020-09-01', '5年8個月', '日班', '低', '正常', '面談排程 8 場'],
  ['E118', 'PX', '彭欣', '財務部', '成本分析師', '2019-12-16', '6年5個月', '日班', '低', '已檢核', '成本中心調整 1 筆'],
  ['E126', 'TN', '唐寧', '製作部', '剪輯師', '2023-05-03', '3年0個月', '彈性班', '中', '正常', '專案加班 3 小時'],
  ['E139', 'MH', '馬浩', '工程部', '燈光技師', '2018-03-27', '8年2個月', '輪班', '中', '檢核中', '班別輪換 4 次'],
]

export const employees = [
  ...baseEmployees,
  ...extraEmployees.map(
    ([id, initials, name, department, title, manager, hireDate, tenure, shiftType, risk, payrollStatus, note], index) => ({
      id,
      initials,
      name,
      department,
      title,
      manager,
      hireDate,
      tenure,
      status: '在職',
      risk,
      contractType: '不定期契約',
      shiftType,
      profileCompleteness: 92 + (index % 7),
      pendingTasks: (index % 4) + 1,
      lastChangeShort: ['調任', '班表', '薪資', '資料'][index % 4],
      lastChange: `${department} 近期資料更新，${note}`,
      modules: {
        contract: { value: '正常', detail: `契約資料完整，入職日 ${hireDate}` },
        attendance: { value: index % 3 === 0 ? '需確認' : '正常', detail: note },
        payroll: { value: payrollStatus, detail: '月結與津貼資料同步中' },
        shift: { value: shiftType, detail: `目前排班型態為${shiftType}` },
        movement: { value: `${(index % 5) + 2} 筆`, detail: '職務、班表或主管異動歷程保留中' },
      },
      timeline: [
        { date: '2026/05', title: '資料更新', detail: `${department} 近期資料已同步` },
        { date: '2026/02', title: '班表調整', detail: `${shiftType}規則已重新確認` },
        { date: '2025/09', title: '人員異動', detail: note },
      ],
      detailCards: [
        { label: '契約提醒', value: '正常', detail: '到期日與附件皆已確認' },
        { label: '本月出勤', value: `${18 + (index % 5)} 天`, detail: note },
        { label: '薪資狀態', value: payrollStatus, detail: '津貼、保險與工時資料已連動' },
      ],
      records: [
        { time: '09:05', title: '主檔更新', detail: `${department} 人員資訊同步完成` },
        { time: '09:19', title: '出勤紀錄', detail: note },
        { time: '09:33', title: '薪資資料', detail: `${payrollStatus}，等待月結批次` },
      ],
    }),
  ),
]

export const moduleDefinitions = [
  { id: 'contract', icon: 'CT', label: '勞動契約' },
  { id: 'attendance', icon: 'AT', label: '考勤紀錄' },
  { id: 'payroll', icon: 'PY', label: '工資獎金' },
  { id: 'shift', icon: 'SH', label: '排班管理' },
  { id: 'movement', icon: 'MV', label: '異動歷程' },
]

export const secondaryViews = [
  {
    id: 'contract',
    label: '勞動契約',
    caption: '續約與附件',
    description: '定期契約、續約提醒、附件管理與到期處理。',
    tags: ['續約提醒', '附件管理', '年資起算'],
  },
  {
    id: 'attendance',
    label: '考勤管理',
    caption: '請假與出勤',
    description: '請假、加班、補登、異常出勤與到班狀態。',
    tags: ['請假流程', '補登處理', '異常提醒'],
  },
  {
    id: 'payroll',
    label: '薪資管理',
    caption: '月結與津貼',
    description: '薪資試算、津貼、保險扣繳與月結檢查。',
    tags: ['月結試算', '津貼計算', '扣繳設定'],
  },
  {
    id: 'shift',
    label: '排班管理',
    caption: '班表規則',
    description: '多班別、輪班、彈性班與部門排班規則。',
    tags: ['多班制', '輪班規則', '班表查詢'],
  },
  {
    id: 'training',
    label: '教育訓練',
    caption: '課程與證照',
    description: '課程報名、訓練時數、證照提醒與發展紀錄。',
    tags: ['課程報名', '時數追蹤', '證照提醒'],
  },
  {
    id: 'settings',
    label: '系統設定',
    caption: '角色與權限',
    description: '角色管理、資料範圍、權限矩陣與系統參數。',
    tags: ['RBAC', '資料範圍', '系統參數'],
  },
]

export const modulePages = {
  contract: {
    eyebrow: 'Contract Overview',
    title: '勞動契約',
    summary: [
      { label: '契約總數', value: '1,214', caption: '在職員工全數建檔' },
      { label: '本月到期', value: '12', caption: '含定期契約與續約提醒' },
      { label: '待補附件', value: '8', caption: '身分證明或簽署檔' },
      { label: '轉不定期', value: '3', caption: '年資條件即將達成' },
    ],
    columns: ['員工', '部門', '契約類型', '期間', '到期狀態', '附件'],
    rows: [
      ['陳思羽', '節目部', '定期契約', '2025/07/01 - 2026/06/30', '30 日內到期', '待補件'],
      ['周立恆', '工程部', '不定期契約', '2019/04/12 -', '正常', '完整'],
      ['許婕', '公關部', '定期契約', '2024/09/01 - 2026/08/31', '續約評估中', '完整'],
      ['吳佳蓉', '新聞部', '不定期契約', '2019/03/04 -', '正常', '完整'],
    ],
    sideTitle: '近期提醒',
    highlights: [
      { title: '7 日內到期', detail: '3 位員工待主管確認續約條件', tone: 'warn' },
      { title: '附件補件', detail: '8 份附件尚未完成歸檔', tone: 'cool' },
      { title: '年資臨界', detail: '3 位定期契約接近轉不定期條件', tone: 'good' },
    ],
  },
  attendance: {
    eyebrow: 'Attendance Center',
    title: '考勤管理',
    summary: [
      { label: '今日到班率', value: '96%', caption: '含現場與遠端' },
      { label: '異常出勤', value: '7', caption: '遲到、漏卡、工時衝突' },
      { label: '補登申請', value: '13', caption: '待主管或人資確認' },
      { label: '加班偏高', value: '5', caption: '連續兩週超過提醒門檻' },
    ],
    columns: ['員工', '類型', '時間', '狀態', '處理人'],
    rows: [
      ['吳佳蓉', '加班偏高', '05/31 22:10', '待覆核', '陳副理'],
      ['沈立安', '漏打卡', '06/01 09:12', '待補登', '新聞部助理'],
      ['林品妤', '請假申請', '06/03 全天', '已核准', '周主任'],
      ['唐寧', '班表衝突', '06/01 晚班', '待調整', '製作部'],
    ],
    sideTitle: '班別與提醒',
    highlights: [
      { title: '輪班人數', detail: '工程部與新聞部共 46 人輪值中', tone: 'cool' },
      { title: '逾時提醒', detail: '5 位員工工時接近法遵上限', tone: 'warn' },
      { title: '補登完成', detail: '今日已完成 9 筆補登處理', tone: 'good' },
    ],
  },
  payroll: {
    eyebrow: 'Payroll Console',
    title: '薪資管理',
    summary: [
      { label: '月結進度', value: '93%', caption: '本月批次完成 7/8' },
      { label: '待覆核', value: '11', caption: '加班費與津貼差異' },
      { label: '津貼異常', value: '4', caption: '夜點、專案與輪班津貼' },
      { label: '批次完成', value: '7', caption: '保險扣繳已更新' },
    ],
    columns: ['員工', '異常項目', '影響欄位', '狀態', '覆核人'],
    rows: [
      ['王以安', '提前給薪參數', '薪資試算', '檢核中', '黃主任'],
      ['吳佳蓉', '夜點津貼', '津貼計算', '待覆核', '薪酬組'],
      ['彭欣', '成本中心異動', '薪資分攤', '已更新', '財務部'],
      ['馬浩', '輪班津貼', '工資明細', '待確認', '工程部主管'],
    ],
    sideTitle: '批次流程',
    highlights: [
      { title: '出勤匯入', detail: '最後更新 09:40，資料來源考勤門禁', tone: 'good' },
      { title: '保險扣繳', detail: '本月規則與基準薪資已同步', tone: 'cool' },
      { title: '封存前檢查', detail: '剩餘 1 個批次等待主管覆核', tone: 'warn' },
    ],
  },
  shift: {
    eyebrow: 'Shift Board',
    title: '排班管理',
    summary: [
      { label: '班別數', value: '14', caption: '日班、晚班、輪班、彈性班' },
      { label: '輪班人數', value: '46', caption: '新聞、工程與製作支援' },
      { label: '異常班表', value: '6', caption: '跨部門支援與休息不足' },
      { label: '待確認', value: '9', caption: '下週班表尚未核定' },
    ],
    columns: ['員工', '部門', '本週班別', '支援區段', '狀態', '主管'],
    rows: [
      ['何紹安', '工程部', '輪班', '棚內支援', '已排定', '林副理'],
      ['唐寧', '製作部', '彈性班', '晚間剪輯', '待確認', '製作部主管'],
      ['吳佳蓉', '新聞部', '晚班', '採訪支援', '已排定', '陳副理'],
      ['馬浩', '工程部', '輪班', '直播支援', '休息檢查', '工程部主管'],
    ],
    sideTitle: '班表摘要',
    highlights: [
      { title: '多班制', detail: '14 種班別規則已套用到部門模板', tone: 'good' },
      { title: '跨部門支援', detail: '本週共有 8 筆臨時支援安排', tone: 'cool' },
      { title: '休息不足', detail: '2 筆排班需重新確認間隔工時', tone: 'warn' },
    ],
  },
  training: {
    eyebrow: 'Learning Center',
    title: '教育訓練',
    summary: [
      { label: '本月課程', value: '18', caption: '內訓與外訓共計' },
      { label: '完成率', value: '89%', caption: '全體員工平均完成率' },
      { label: '待補課', value: '27', caption: '含資安與法遵課程' },
      { label: '證照提醒', value: '6', caption: '技術與工程人員為主' },
    ],
    columns: ['課程', '對象', '完成率', '開課日', '狀態', '負責單位'],
    rows: [
      ['資安基礎訓練', '全體員工', '92%', '06/05', '補課追蹤', '資訊部'],
      ['直播設備安全', '工程部', '81%', '06/08', '進行中', '工程部'],
      ['勞動法令更新', '主管與人資', '76%', '06/11', '報名中', '人資室'],
      ['內容製播流程', '節目部', '88%', '06/14', '已開課', '節目部'],
    ],
    sideTitle: '學習提醒',
    highlights: [
      { title: '必修課程', detail: '資安訓練還有 13 人未完成', tone: 'warn' },
      { title: '證照追蹤', detail: '工程部 3 張證照 30 日內到期', tone: 'cool' },
      { title: '完成率最佳', detail: '人資室本月完成率 100%', tone: 'good' },
    ],
  },
  settings: {
    eyebrow: 'System Settings',
    title: '系統設定',
    summary: [
      { label: '啟用角色', value: '16', caption: '依模組與資料範圍拆分' },
      { label: '權限異動', value: '5', caption: '本週新增與調整' },
      { label: '同步狀態', value: '99.2%', caption: 'AD / ERP / 考勤門禁' },
      { label: '備份狀態', value: '正常', caption: '昨夜備份已完成' },
    ],
    columns: ['角色', '資料範圍', '模組數', '最近異動', '狀態', '管理者'],
    rows: [
      ['HR Admin', '全公司', '12', '05/31 權限調整', '啟用中', '資訊部'],
      ['Payroll Lead', '薪酬資料', '5', '06/01 新增匯出限制', '啟用中', '人資室'],
      ['Dept Manager', '部門資料', '7', '05/29 簽核權限更新', '啟用中', '資訊部'],
      ['Training Owner', '訓練模組', '3', '05/28 新增證照提醒', '啟用中', '人資室'],
    ],
    sideTitle: '系統摘要',
    highlights: [
      { title: 'AD 同步', detail: '最近同步 09:42，無失敗筆數', tone: 'good' },
      { title: '權限矩陣', detail: '本週新增 2 組部門資料範圍規則', tone: 'cool' },
      { title: '備份檢查', detail: '上次還原演練時間 05/25', tone: 'warn' },
    ],
  },
}

export const dashboard = {
  totalEmployees: '1,214',
  monthlyChanges: 28,
  attendanceRate: 96,
  payrollCheck: 93,
  turnover: [
    { label: '節目部', value: 18 },
    { label: '新聞部', value: 24 },
    { label: '資訊部', value: 9 },
    { label: '人資室', value: 6 },
  ],
  attendance: [
    { label: '到班', value: 852, tone: 'good' },
    { label: '遠端', value: 129, tone: 'cool' },
    { label: '請假', value: 41, tone: 'warn' },
  ],
}
